# Generated by Django 5.1.2 on 2024-11-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_interest_teacher_department_remove_teacher_interests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament', models.CharField(choices=[('system_desygn', 'Cистемного проектування'), ('radio_physic_computer_tech', 'Радіофізики та комп’ютерних технологій'), ('computer_system', 'Радіоелектронних і комп’ютерних систем'), ('optoelec_it', 'Оптоелектроніки та інформаційних технологій')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departament'),
        ),
    ]
