# Generated by Django 5.1.2 on 2024-11-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_departament_remove_teacher_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departament',
            name='departament',
            field=models.CharField(choices=[('Cистемного проектування', 'Cистемного проектування'), ('Радіофізики та комп’ютерних технологій', 'Радіофізики та комп’ютерних технологій'), ('Радіоелектронних і комп’ютерних систем', 'Радіоелектронних і комп’ютерних систем'), ('opОптоелектроніки та інформаційних технологій', 'Оптоелектроніки та інформаційних технологій')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='thesis_topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
