# Generated by Django 5.1.2 on 2024-11-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_course_student_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='departament',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='departament',
            name='departament',
        ),
        migrations.AddField(
            model_name='departament',
            name='department',
            field=models.CharField(choices=[('Cистемного проектування', 'Cистемного проектування'), ('Радіофізики та комп’ютерних технологій', 'Радіофізики та комп’ютерних технологій'), ('Радіоелектронних і комп’ютерних систем', 'Радіоелектронних і комп’ютерних систем'), ('Оптоелектроніки та інформаційних технологій', 'Оптоелектроніки та інформаційних технологій')], max_length=50, null=True),
        ),
    ]
