# Generated by Django 5.1.2 on 2024-11-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_departament_teacher_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='department',
            new_name='departament',
        ),
    ]
