# Generated by Django 5.1.2 on 2024-11-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_department_departament_departament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='departament',
        ),
    ]
